### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/eda_mds#36]
Discuss the feedback here!

**Comment by srfrew** [comment]
Summary of feedback from Milestone 1: 

**Software package project structure**
- [x] `eda_mds.py` is an empty unnecessary file
- [x] Recommended adding links to the reference pandas functions

**Function documentation** 
`info_na`
- [x] missing returns in documentation
- [x] documentation of output values was vague 
- [x] missing example usage

`cat_var_stats`
- [x] missing example usage

**GitHub Issues**
- [x] Issues created but not used well for communication

**Comment by srfrew** [comment]
Note that `info_na` has been corrected in Milestone 2 and Milestone 3

**Comment by nicolebid** [comment]
added an example for describe_outliers and the links to readme
