### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/eda_mds#49]
### Milestone 1:
- [x] unnecessary files present in repo: `eda_mds.py`, `__init__.py
- [x] `info_na.py` missing returns 
- [x] `info_na.py` missing example
- [x] `cat_var_stats.py` missing example
- [x] `describe_outliers.py` missing example
- [x] review and clarify block structure 

### Milestone 2: 
Structure
- [x] Add explicit instructions to install the package in README
- [x] remove empty `__init__.py` in `src/` folder
Functions
- [x] `cat_var_stats.py` is not commented
- [x] `cat_var_stats.py` missing examples in documentation
- [x] `describe_outliers.py` missing examples in documentation
- [x] `info_na.py` missing examples in documentation
- [x] `cor_eda`: clarify: "The DataFrame should include various types of variables" in documentation
- [x] `cor_eda`: comments from reviewer to be addressed or mentioned
    - It is not clear in cor_eda when na_handling=="value" which value will be replaced. I see the comment in line 43 "for demonstration we use 0" but this is confusing. Is it going to be always zero? Can the user choose this value?
    - Is there a specific reason that when checking the input in cor_eda you are returning an error message but not raising the error with a message? When you raise an error, it interrupts the normal flow of the program and this allows for more robust error handling. Returning an error message as a string, however, means that the program will continue executing, and it becomes the responsibility of the calling code or user to check if the return value is an error message or a valid result.
    - Also, numerical_data.shape[1] == 0 does not necessarily mean that there are no numerical columns and "There are no numerical columns" in this case can be confusing.

Tests
- [x] Add documentation on how to run the test suite
- [x] Add dependencies to calculate code coverage 
- [x] Address test failure in `failure: tests/test_info_na.py:34: AssertionError`
- [x] Add comments to `test_cat_var_stats.py` 
- [x] Add comments to `test_describe_outliers.py` 
- [x] Add comments to `test_cor_eda.py`
- [x] Improve code formatting (lint) for `test_cor_eda`
- [x] ensure code coverage is 100%

Communication
- [x] Use GitHub issues for consistent communication

**Comment by srfrew** [comment]
[Peer Review 1](https://github.com/UBC-MDS/software-review-2024/issues/22#issuecomment-1916043100): 
- [x] Vignette "options for categorical columns" table too large. Figure out how to scroll or truncate
- [x] Installations instructions should be in readme, at least in short form from PyPI
- [x] Update badges 
- [x] Add link to vignette in readme
- [x] review dependencies: move some to dev and trim unused

**Comment by nicolebid** [comment]
[Peer Review 2](https://github.com/UBC-MDS/software-review-2024/issues/22#issuecomment-1916184606)

- [x] README.md: installation instructions is repeated twice in 
- [x] README.md: in installation instructions,  instead of 'download' repo, use the word 'clone' 
- [x] README.md: in installation instruction remind to run 'poetry install' from the root directory of the repository where pyproject.toml (Although, it's not needed after its on PyPI) 
- [x] README.md: include a clickable link to vignette in usage 
- [x] readthedocs: reduce size of table in vignette so it doesn't overflow (if possible)
- [x] readthedocs example: Include a small section on your vignette to address how to avoid running into common errors in your functions, since functions have several "exception handling" mechanisms
- [x] cat_var_stat.py: increase code coverage to at least 50%, if possible.

**Comment by korayt** [comment]
[Peer Review 3](https://github.com/UBC-MDS/software-review-2024/issues/22#issuecomment-1916542901)

- [x] Installation link has been provided two times (Under Installation, Usage Sections)
- [x] describe_outliers: describe_outliers function's output is not rendered properly
- [x] include examples under usage section (like add how to import your package, how to call your functions)
- [x] put installation steps in README.
- [x] add the command for running/viewing the detailed test coverage report in README
- [x] add more badges to README

**Comment by paolocodina** [comment]
[Peer Review 4](https://github.com/UBC-MDS/software-review-2024/issues/22#issuecomment-1916542901)

- [x] Add test instructions to Readme
- [x] Include test coverage package in the pyproject.toml
- [x] Make the format in example part and docstring per function script consistent (PEP 8 guidelines)
- [x] Add the jupyter notebook package in the pyproject.toml to run example notebook
- [x] unnecessary files present in repo: `eda_mds.py`, `__init__.py
- [x] `cor_eda`: clarify: "The DataFrame should include various types of variables" in documentation
- [x] `cor_eda`: comments from reviewer to be addressed or mentioned
    - It is not clear in cor_eda when na_handling=="value" which value will be replaced. I see the comment in line 43 "for demonstration we use 0" but this is confusing. Is it going to be always zero? Can the user choose this value?
    - Is there a specific reason that when checking the input in cor_eda you are returning an error message but not raising the error with a message? When you raise an error, it interrupts the normal flow of the program and this allows for more robust error handling. Returning an error message as a string, however, means that the program will continue executing, and it becomes the responsibility of the calling code or user to check if the return value is an error message or a valid result.
    - Also, numerical_data.shape[1] == 0 does not necessarily mean that there are no numerical columns and "There are no numerical columns" in this case can be confusing.

**Comment by korayt** [comment]
Feedbacks that are not about a function
### Milestone 1
- [x] unnecessary files present in repo: `eda_mds.py`, `__init__.py
- [x] review and clarify block structure 
### Milestone 2: 
Structure
- [x] Add explicit instructions to install the package in README
- [x] remove empty `__init__.py` in `src/` folder
Tests
- [x] Add documentation on how to run the test suite
- [x] Add dependencies to calculate code coverage 
- [x] ensure code coverage is 100%
### PR1
- [x] Vignette "options for categorical columns" table too large. Figure out how to scroll or truncate
- [x] Installations instructions should be in readme, at least in short form from PyPI
- [x] Update badges 
- [x] Add link to vignette in readme
- [x] review dependencies: move some to dev and trim unused
### PR2
- [x] README.md: installation instructions is repeated twice in 
- [x] README.md: in installation instructions,  instead of 'download' repo, use the word 'clone' 
- [x] README.md: in installation instruction remind to run 'poetry install' from the root directory of the repository where pyproject.toml (Although, it's not needed after its on PyPI) 
- [x] README.md: include a clickable link to vignette in usage 
- [x] readthedocs: reduce size of table in vignette so it doesn't overflow (if possible)
- [x] readthedocs example: Include a small section on your vignette to address how to avoid running into common errors in your functions, since functions have several "exception handling" mechanisms
### PR3
- [x] Installation link has been provided two times (Under Installation, Usage Sections)
- [x] include examples under usage section (like add how to import your package, how to call your functions)
- [x] put installation steps in README.
- [x] add the command for running/viewing the detailed test coverage report in README
- [x] add more badges to README
### PR4
- [x] Add test instructions to Readme
- [x] Include test coverage package in the pyproject.toml
- [x] Make the format in example part and docstring per function script consistent (PEP 8 guidelines)
- [x] Add the jupyter notebook package in the pyproject.toml to run example notebook
- [x] unnecessary files present in repo: `eda_mds.py`, `__init__.py

**Comment by srfrew** [comment]
Writing a note here for myself to lint all our files with the `black` formatting styler before we submit!!
